spring:
  application:
    name: kick-app

  r2dbc:
    name: kick_app
    password: password123
    username: admin
    url: r2dbc:postgresql://localhost:5432/kick_app
    pool:
      max-size: 20

  flyway:
    validate-on-migrate: true
    user: admin
    password: password123
    url: jdbc:postgresql://localhost:5432/kick_app
    schemas: ["kick_app"]

  data:
    mongodb:
      uri: mongodb://admin:password123@localhost:6000/kick_app?authSource=admin
      database: kick_app

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/kick-app

keycloak:
  realm: kick-app

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password
  bucket: user-images

server:
  port: 8085

logging:
  level:
    org.springframework.security: INFO

