definitions:
  creategroup.Response:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  createuser.Response:
    properties:
      email:
        type: string
      firstName:
        type: string
      groups:
        items:
          type: string
        type: array
      id:
        type: string
      lastName:
        type: string
      nickName:
        type: string
    type: object
  getgroupdetails.Response:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  getgroups.Response:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  loginuser.Response:
    properties:
      email:
        type: string
      firstName:
        type: string
      groups:
        items:
          type: string
        type: array
      id:
        type: string
      lastName:
        type: string
      nickName:
        type: string
    type: object
info:
  contact: {}
paths:
  /group:
    post:
      description: user creates a new Group with a new name
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/creategroup.Response'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: creates a new Group
      tags:
      - group
  /group/{groupId}:
    get:
      description: get group details by group id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/getgroupdetails.Response'
        "400":
          description: Bad Request
      summary: get group details by group id
      tags:
      - group
  /group/user:
    delete:
      description: user leaves a group
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: user leaves a group
      tags:
      - group
    post:
      description: invite a user to a group
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: invite a user to a group
      tags:
      - group
    put:
      description: handels if a user accepts or declines an invite to a group
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: handels invited user response
      tags:
      - group
  /group/user/{userId}:
    get:
      description: get groups by user id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/getgroups.Response'
            type: array
        "400":
          description: Bad Request
      summary: get groups by user id
      tags:
      - group
  /message/read:
    post:
      consumes:
      - application/json
      description: logs in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/loginuser.Response'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: logs in user
      tags:
      - user
  /player/role:
    put:
      consumes:
      - application/json
      description: updates role of a player
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: updates role of a player
      tags:
      - player
  /user:
    post:
      consumes:
      - application/json
      description: creates new user
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/createuser.Response'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: creates new user
      tags:
      - user
  /user/login:
    put:
      consumes:
      - application/json
      description: reads a message
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: reads a message
      tags:
      - user
swagger: "2.0"
