name: Java

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend-kotlin/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend-kotlin/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests with Maven
        working-directory: ./backend-kotlin
        run: mvn test